logging:
  level:
    root: INFO
    org.dotwebstack: DEBUG

dotwebstack:
  config: dotwebstack.yaml
  postgres:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    database: postgres
    schema: dbeerpedia
