logging:
  level:
    root: INFO
    org.dotwebstack: DEBUG

dotwebstack:
  rdf4j:
    shape:
      graph: https://github.com/dotwebstack/beer/shapes
      prefix: https://github.com/dotwebstack/beer/shapes#
